name: SaveNotDrip Tests

on: [ push, pull_request ]
    
jobs:
  Windows:
    name: Compiling Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Haxe environment
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest
      - name: Install Haxe Libraries
        run: |
          haxelib install utest --quiet
          haxelib install hxcpp --quiet
      - name: Compile The Test
        run: |
          cd ${{ github.workspace }}
          haxe test.hxml
      - name: Upload Windows/CPP Executable
        uses: actions/upload-artifact@v4
        with:
          name: WindowsakaCPP
          path: ${{ github.workspace }}/extras/testing/build/windows/
      - name: Upload html5/js file
        uses: actions/upload-artifact@v4
        with:
          name: HTML5akaJS
          path: ${{ github.workspace }}/extras/testing/build/javascript/
